version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install
  build:
    commands:
      - npm run build
      - docker build -t my-node-app .

  post_build:
    commands:
      - echo "Build completed successfully"

artifacts:
  files:
    - "**/*"
  base-directory: .
